object Versions {
    val KTX_CORE_VERSION = "1.5.0"
    val APP_COMPAT = "1.3.0"
    val MATERIAL_DESIGN =  "1.3.0"
    val CONSTRAINT_LAYOUT =  "1.3.0"
    val KOTLIN_STBLIB =  "1.5.10"
    val JUNIT_TEST =  "4.12"
    val JUNIT_EXT_TEXT =  "1.1.2"
    val ESPRESSO =  "3.3.0"
    val KOTLIN_CORE = "2.2.2"
    val COROUTINE_CORE = "1.4.3"
    val MOCKITO_CORE = "3.9.0"
    val MOCKITO_KOTLIN = "2.2.0"
    val COROUTINE_TEST = "1.4.2"
    val RECYCLER_VIEW = "1.2.0"
    val COROUTINES_ANDROID = "1.4.3"
    val LIFECYCLE_EXTENSIONS = "2.2.0"
    val LIFECYCLE_RUNTIME = "2.3.1"
    val LIFECYCLE_VIEWMODEL = "2.3.1"
    val PICASSO = "2.71828"
}